name: Test demography project with renv

on: [push, pull_request]

jobs:
  test-renv:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-renv@v2

    - name: Run tests
      run: Rscript -e 'testthat::test_dir("tests/")'


